---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi

steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: ch1ch1/webp
    tags: [ "latest" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
- name: notification success
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
        "extras": {
        "client::display": {
        "contentType": "text/markdown"
        }
      },
       "message": "![](https://ch1ch1.fr/img/ok.webp) **{{ commit.author }}** as updated **{{ repo.name }}**, result: **{{ build.status }}**.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ success ]
- name: notification failure
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
        "extras": {
        "client::display": {
        "contentType": "text/markdown"
        }
      },
       "message": "![](https://ch1ch1.fr/img/nok.webp) **{{ commit.author }}** as updated **{{ repo.name }}**, result: **{{ build.status }}**.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ failure ]

---
kind: signature
hmac: 67d35fbfc29cb1b15d91df007499bc71fae4cc032cbb73f9eccdd4f47a9c67fd

...
