---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi

steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: ch1ch1/webp
    tags: [ "latest" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
---
kind: signature
hmac: 497c1e0c83f4616fdb53877cfd69ecaa932233e7ba22c5ac8fb2da9f20bcb507

...
